version: "1.0"
id: local
name: Local Machine
name_zh: 本机
type: docker_local

detection:
  method: local
  requirements:
    - docker_installed
    - docker_running

docker:
  compose_file: assets/docker/docker-compose.yml

  environment:
    TZ: Asia/Shanghai
    OPC_UA_SERVER: "{{opc_ua_server}}"

  options:
    project_name: missionpack_knn
    remove_orphans: true
    build: false

  services:
    - name: app
      port: 8280
      health_check_endpoint: /api/v1/health
      required: true

user_inputs:
  - id: opc_ua_server
    name: OPC-UA Server Address
    name_zh: OPC-UA 服务器地址
    type: text
    default: "opc.tcp://localhost:4841"
    placeholder: "opc.tcp://192.168.1.100:4840"
    description: OPC-UA server address (use default for built-in simulator)
    description_zh: OPC-UA 服务器地址（使用默认值连接内置模拟器）
    required: false

pre_checks:
  - type: docker_version
    min_version: "20.0"
    description: Check Docker version
  - type: port_available
    ports:
      - 8280
      - 4841
    description: Check if ports are available
  - type: disk_space
    min_gb: 1
    description: Check available disk space

post_deployment:
  open_browser: true
  url: "http://localhost:8280"
